### ISSUE TITLE
Darstellung der Planungszone nicht nach MGDM

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-wms#3]
### Beschreibung

![Darstellung_Planungszone_MGDM](https://user-images.githubusercontent.com/3929984/163352481-933925b8-02d0-4a6c-849d-6044a82dad92.jpg)
![Linie_Planungszone](https://user-images.githubusercontent.com/3929984/163352491-f1ea9239-3868-41d4-a76c-a7ee02402743.jpg)
![Farbe](https://user-images.githubusercontent.com/3929984/163352500-313a6f3d-f556-4680-a8ee-349f7dfb5079.jpg)

https://www.are.admin.ch/are/de/home/raumentwicklung-und-raumplanung/grundlagen-und-daten/minimale-geodatenmodelle/Planungszonen.html

Hinweis.... Wir haben nur Planungszone der Gemeinde.

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by Luescher** [comment]
Der Legende Text sollte "Gemeinde" sein. Bin gerade ein wenig unsicher, ob die Darstellung auch für "Kanton" und "andere" machen müssen. Die haben wir dann einfach nicht.
![alle](https://user-images.githubusercontent.com/3929984/163353459-996dcf63-a19a-4232-8bff-59895a38c095.jpg)

**Comment by edigonzales** [comment]
Ich glaube, die braucht es nicht. Es gibt ja keine "vollständige Legende" mehr.

**Comment by edigonzales** [comment]
fixed https://github.com/sogis-oereb/oereb-wms/commit/7bfd96d78286ceedbd440256bf325838d0c7a3f0
