### ISSUE TITLE
Im Legendentext hat es einen Punkt bei "Belastet, weder überwachungs- noch sanierungsbedürftig" 

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-wms#4]
### Beschreibung

Punkt "." entfernen
![kbs](https://user-images.githubusercontent.com/3929984/164432665-5c99d144-30e7-4a12-8be6-8631fdab9883.jpg)

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by edigonzales** [comment]
Fehler im XTF von geops.

![Screenshot 2022-04-21 at 14 27 35](https://user-images.githubusercontent.com/2767800/164457844-3ba1519a-6cea-447a-8e4c-1a29499eca42.png)
.
