### ISSUE TITLE
Symbol ist abgeschnitten bei Grundwasserschutzzone

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-wms#5]
### Beschreibung

Im Web GIS Client und im PDF
![symbol_abgeschnitten](https://user-images.githubusercontent.com/3929984/164439665-c750f793-2af1-4c2c-a130-6523d1ddf781.jpg)

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by edigonzales** [comment]
Bein Grundwasserschutz und bei den Planungszonen gefixed. Nicht perfekt, aber viel besser. Falls du noch andere siehst oder schon weisst, bitte melden.




![Screenshot 2022-04-22 at 06 50 40](https://user-images.githubusercontent.com/2767800/164605537-fe2d956d-27be-4efc-a466-312b9ce5ce46.png)

![Screenshot 2022-04-22 at 06 50 47](https://user-images.githubusercontent.com/2767800/164605541-b6b4f31b-ed7d-4d83-8e06-039c7f8fef6b.png)

**Comment by edigonzales** [comment]
fixed
